26_logging_tasks.py[LINE:31]# DEBUG    [2025-01-14 15:13:12,548] Сообщение для отладки
26_logging_tasks.py[LINE:32]# INFO     [2025-01-14 15:13:12,549] Сообщение обыкновенное информационнная
26_logging_tasks.py[LINE:33]# WARNING  [2025-01-14 15:13:12,549] Предупреждение
26_logging_tasks.py[LINE:34]# ERROR    [2025-01-14 15:13:12,550] Ошибка
26_logging_tasks.py[LINE:35]# CRITICAL [2025-01-14 15:13:12,550] Полный крах
